<?php

return array(
    '' => 'site/index',
    'login' => 'site/login',
    'sign-up' => 'site/UserRegister',
    'coupons' => 'products/coupons',
    'submit-deals' => 'myaccount/SubmitDeal',
    'products' => 'products/Detail',
    'My-Account' => 'Myaccount/index',
    'My-Profile' => 'Myaccount/index',
    'reset-password' => 'Myaccount/ResetPassword',
    'Forgot-password' => 'ForgotPassword/index',
    'New-Address' => 'Myaccount/NewAddressBook',
    'Address-Book' => 'Myaccount/AddressBook',
    'Account-settings' => 'Myaccount/UserSettings',
    'Account-settings' => 'Myaccount/VendorSettings',
    'category' => 'products/Category',
    'Dailydeals' => 'products/Daily',
    'Hotdeals' => 'products/hot',
    'Wholesaledeals' => 'products/wholesale',
    'my-products' => 'Products/MyProducts',
    'Discount-coupon-generation' => 'Myaccount/CouponGeneration',
    'Newsletter-Subscription' => 'Myaccount/Newsletter',
    'add-products' => 'Products/AddProducts',
    'view-products' => 'Products/MyProducts',
    'order-history' => 'Myaccount/UserOrderHistory',
    'order-history' => 'Myaccount/VendorOrderHistory',
    'Bargain-zone' => 'products/bargain',
    'plan-creation' => 'Myaccount/SelectPlan',
    'plan-upgration' => 'Myaccount/UpgradePlan',
    'email-verification' => 'site/UserActivation',
    'email-verification' => 'site/VendorActivation',
//    'ss' => '?name',
    'merchant-registration' => 'registration/merchantDetails/create',
//    'merchant-activation' => 'registration/merchantDetails/UserActivation',
//    'login' => 'site/login',
    'logout' => 'site/logout',
    '<controller:\w+>/<id:\d+>' => '<controller>/view',
    '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
);

